-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LSTM_Top_exp_generic_double_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of LSTM_Top_exp_generic_double_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv71_58B90BFBE8E7BCD5E4 : STD_LOGIC_VECTOR (70 downto 0) := "10110001011100100001011111110111110100011100111101111001101010111100100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv58_10 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv49_0 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_6A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101010";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv13_1C02 : STD_LOGIC_VECTOR (12 downto 0) := "1110000000010";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_69 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101001";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv64_7FFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "0111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv64_7FF0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0111111111110000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_5C55 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000101110001010101";

attribute shreg_extract : string;
    signal table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0 : STD_LOGIC_VECTOR (57 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0 : STD_LOGIC_VECTOR (25 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1 : STD_LOGIC_VECTOR (25 downto 0);
    signal table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0 : STD_LOGIC_VECTOR (41 downto 0);
    signal es_sign_fu_284_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal es_sign_reg_1104_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_reg_1104_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_reg_1109_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_reg_1116_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal e_frac_2_fu_362_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal e_frac_2_reg_1122 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1127 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1127_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1127_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln229_fu_388_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln229_reg_1133 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln309_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_reg_1138_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1146_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln227_fu_417_p1 : STD_LOGIC_VECTOR (70 downto 0);
    signal sext_ln227_reg_1151 : STD_LOGIC_VECTOR (70 downto 0);
    signal sext_ln227_reg_1151_pp0_iter2_reg : STD_LOGIC_VECTOR (70 downto 0);
    signal sext_ln229_1_fu_421_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln229_1_reg_1156 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_fix_l_reg_1161 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_reg_1167 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1167_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln255_fu_479_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter2_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter3_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter4_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter5_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter6_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter7_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter8_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln255_reg_1177_pp0_iter9_reg : STD_LOGIC_VECTOR (58 downto 0);
    signal shl_ln230_fu_486_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln230_reg_1182 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln230_fu_491_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ashr_ln230_reg_1187 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln309_2_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_2_reg_1197_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_exp_fu_564_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter5_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter6_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter7_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter8_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter9_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter10_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter11_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter12_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter13_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter14_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter15_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter16_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter17_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter18_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter19_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter20_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter21_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter22_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter23_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter24_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter25_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_reg_1202_pp0_iter26_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_8_reg_1214 : STD_LOGIC_VECTOR (57 downto 0);
    signal m_diff_hi_reg_1219 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter12_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter13_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter14_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter15_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter16_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter17_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter18_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_diff_hi_reg_1219_pp0_iter19_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224 : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter12_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter13_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter14_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter15_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter16_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter17_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter18_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter19_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z2_reg_1224_pp0_iter20_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z3_fu_618_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal Z3_reg_1231 : STD_LOGIC_VECTOR (7 downto 0);
    signal Z3_reg_1231_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Z4_fu_628_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal Z4_reg_1236 : STD_LOGIC_VECTOR (34 downto 0);
    signal exp_Z4_m_1_fu_669_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal exp_Z4_m_1_reg_1251 : STD_LOGIC_VECTOR (35 downto 0);
    signal exp_Z4_m_1_reg_1251_pp0_iter12_reg : STD_LOGIC_VECTOR (35 downto 0);
    signal exp_Z4_m_1_reg_1251_pp0_iter13_reg : STD_LOGIC_VECTOR (35 downto 0);
    signal exp_Z4_m_1_reg_1251_pp0_iter14_reg : STD_LOGIC_VECTOR (35 downto 0);
    signal f_Z3_reg_1257 : STD_LOGIC_VECTOR (25 downto 0);
    signal exp_Z3_m_1_fu_675_p4 : STD_LOGIC_VECTOR (42 downto 0);
    signal exp_Z3_m_1_reg_1262 : STD_LOGIC_VECTOR (42 downto 0);
    signal exp_Z3_m_1_reg_1262_pp0_iter13_reg : STD_LOGIC_VECTOR (42 downto 0);
    signal exp_Z3_m_1_reg_1262_pp0_iter14_reg : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_s_reg_1277 : STD_LOGIC_VECTOR (19 downto 0);
    signal exp_Z2P_m_1_fu_721_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2P_m_1_reg_1287 : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2P_m_1_reg_1287_pp0_iter16_reg : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2P_m_1_reg_1287_pp0_iter17_reg : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2P_m_1_reg_1287_pp0_iter18_reg : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2P_m_1_reg_1287_pp0_iter19_reg : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2P_m_1_reg_1287_pp0_iter20_reg : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_1_reg_1293 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_1_reg_1293_pp0_iter16_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_1_reg_1293_pp0_iter17_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_1_reg_1293_pp0_iter18_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_1_reg_1293_pp0_iter19_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_1_reg_1293_pp0_iter20_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_4_reg_1314 : STD_LOGIC_VECTOR (35 downto 0);
    signal exp_Z1_reg_1319 : STD_LOGIC_VECTOR (57 downto 0);
    signal exp_Z1_reg_1319_pp0_iter22_reg : STD_LOGIC_VECTOR (57 downto 0);
    signal exp_Z1_reg_1319_pp0_iter23_reg : STD_LOGIC_VECTOR (57 downto 0);
    signal exp_Z1_reg_1319_pp0_iter24_reg : STD_LOGIC_VECTOR (57 downto 0);
    signal exp_Z1_reg_1319_pp0_iter25_reg : STD_LOGIC_VECTOR (57 downto 0);
    signal exp_Z1P_m_1_reg_1324 : STD_LOGIC_VECTOR (49 downto 0);
    signal exp_Z1_hi_reg_1329 : STD_LOGIC_VECTOR (49 downto 0);
    signal add_ln297_fu_828_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal add_ln297_reg_1344 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_fu_276_p2 : STD_LOGIC_VECTOR (98 downto 0);
    signal mul_ln297_reg_1349 : STD_LOGIC_VECTOR (98 downto 0);
    signal icmp_ln309_1_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln309_1_reg_1354 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln326_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln326_reg_1361 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln336_fu_891_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln336_reg_1366 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln303_fu_915_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal select_ln303_reg_1371 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln114_fu_642_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln119_fu_647_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln138_fu_702_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln292_fu_754_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local : STD_LOGIC;
    signal table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local : STD_LOGIC;
    signal table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local : STD_LOGIC;
    signal table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local : STD_LOGIC;
    signal grp_fu_268_p0 : STD_LOGIC_VECTOR (42 downto 0);
    signal grp_fu_268_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_fu_272_p0 : STD_LOGIC_VECTOR (48 downto 0);
    signal grp_fu_272_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal grp_fu_276_p0 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_fu_276_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal data_fu_280_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal es_exp_fu_292_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal es_sig_fu_300_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln18_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_1_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_2_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln486_fu_334_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal e_frac_fu_344_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln221_fu_352_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal e_frac_1_fu_356_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal m_exp_fu_338_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln229_fu_378_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln229_fu_384_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal m_frac_l_fu_410_p3 : STD_LOGIC_VECTOR (60 downto 0);
    signal zext_ln229_fu_424_p1 : STD_LOGIC_VECTOR (70 downto 0);
    signal ashr_ln229_fu_428_p2 : STD_LOGIC_VECTOR (70 downto 0);
    signal shl_ln229_fu_434_p2 : STD_LOGIC_VECTOR (70 downto 0);
    signal m_fix_fu_440_p3 : STD_LOGIC_VECTOR (70 downto 0);
    signal m_fix_hi_fu_457_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln230_fu_483_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln_fu_496_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln230_fu_507_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln2_fu_512_p3 : STD_LOGIC_VECTOR (70 downto 0);
    signal grp_fu_1093_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln243_fu_541_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_1_cast_fu_525_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln243_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln243_1_fu_550_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_3_fu_534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln243_fu_556_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_263_p2 : STD_LOGIC_VECTOR (70 downto 0);
    signal and_ln_fu_586_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal sub_ln255_fu_593_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal Z4_ind_fu_632_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal f_Z4_fu_652_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln115_fu_662_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln115_1_fu_665_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_fu_268_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln126_1_fu_709_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln126_fu_712_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln126_fu_717_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln120_fu_706_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal exp_Z2_m_1_fu_737_p4 : STD_LOGIC_VECTOR (48 downto 0);
    signal grp_fu_272_p2 : STD_LOGIC_VECTOR (92 downto 0);
    signal and_ln1_fu_768_p5 : STD_LOGIC_VECTOR (50 downto 0);
    signal zext_ln145_2_fu_782_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln145_fu_785_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln145_1_fu_790_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln145_fu_778_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal exp_Z1P_m_1_l_fu_794_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal shl_ln1_fu_833_p3 : STD_LOGIC_VECTOR (106 downto 0);
    signal zext_ln297_2_fu_840_p1 : STD_LOGIC_VECTOR (106 downto 0);
    signal add_ln297_1_fu_843_p2 : STD_LOGIC_VECTOR (106 downto 0);
    signal tmp_5_fu_849_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_exp_1_fu_857_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_exp_2_fu_862_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_9_fu_869_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_895_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_7_fu_905_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal xor_ln182_fu_923_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_pinf_fu_928_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln185_fu_933_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln185_fu_938_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_exp_fu_968_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal t_fu_973_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln479_fu_980_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln309_fu_957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln309_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln309_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln309_1_fu_998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln185_1_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln309_1_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln185_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln309_1_fu_1021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln309_2_fu_1032_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln309_3_fu_1027_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln309_2_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln309_3_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln309_4_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln309_2_fu_1015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln309_5_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_1_fu_1069_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal retval_1_fu_1069_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal retval_1_fu_1069_p8 : STD_LOGIC_VECTOR (63 downto 0);
    signal retval_1_fu_1069_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal retval_1_fu_1069_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_1093_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_263_ce : STD_LOGIC;
    signal grp_fu_268_ce : STD_LOGIC;
    signal grp_fu_272_ce : STD_LOGIC;
    signal grp_fu_276_ce : STD_LOGIC;
    signal retval_1_fu_1069_p11 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_1093_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_268_p00 : STD_LOGIC_VECTOR (78 downto 0);
    signal grp_fu_268_p10 : STD_LOGIC_VECTOR (78 downto 0);
    signal grp_fu_272_p00 : STD_LOGIC_VECTOR (92 downto 0);
    signal grp_fu_272_p10 : STD_LOGIC_VECTOR (92 downto 0);
    signal grp_fu_276_p00 : STD_LOGIC_VECTOR (98 downto 0);
    signal grp_fu_276_p10 : STD_LOGIC_VECTOR (98 downto 0);
    signal retval_1_fu_1069_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_1_fu_1069_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_1_fu_1069_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_1_fu_1069_p7 : STD_LOGIC_VECTOR (2 downto 0);

    component LSTM_Top_mul_13s_71s_71_5_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (70 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (70 downto 0) );
    end component;


    component LSTM_Top_mul_43ns_36ns_79_3_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (42 downto 0);
        din1 : IN STD_LOGIC_VECTOR (35 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (78 downto 0) );
    end component;


    component LSTM_Top_mul_49ns_44ns_93_5_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (48 downto 0);
        din1 : IN STD_LOGIC_VECTOR (43 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (92 downto 0) );
    end component;


    component LSTM_Top_mul_50ns_50ns_99_5_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (49 downto 0);
        din1 : IN STD_LOGIC_VECTOR (49 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (98 downto 0) );
    end component;


    component LSTM_Top_sparsemux_9_3_64_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        din3 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component LSTM_Top_mac_muladd_16s_15ns_19s_31_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component LSTM_Top_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component LSTM_Top_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component LSTM_Top_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (41 downto 0) );
    end component;



begin
    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_U : component LSTM_Top_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb
    generic map (
        DataWidth => 58,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0,
        ce0 => table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local,
        q0 => table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0);

    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U : component LSTM_Top_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud
    generic map (
        DataWidth => 26,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0,
        ce0 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local,
        q0 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0,
        address1 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1,
        ce1 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local,
        q1 => table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1);

    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U : component LSTM_Top_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe
    generic map (
        DataWidth => 42,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0,
        ce0 => table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local,
        q0 => table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0);

    mul_13s_71s_71_5_0_U54 : component LSTM_Top_mul_13s_71s_71_5_0
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 13,
        din1_WIDTH => 71,
        dout_WIDTH => 71)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => r_exp_reg_1202,
        din1 => ap_const_lv71_58B90BFBE8E7BCD5E4,
        ce => grp_fu_263_ce,
        dout => grp_fu_263_p2);

    mul_43ns_36ns_79_3_0_U55 : component LSTM_Top_mul_43ns_36ns_79_3_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 43,
        din1_WIDTH => 36,
        dout_WIDTH => 79)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_268_p0,
        din1 => grp_fu_268_p1,
        ce => grp_fu_268_ce,
        dout => grp_fu_268_p2);

    mul_49ns_44ns_93_5_0_U56 : component LSTM_Top_mul_49ns_44ns_93_5_0
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 49,
        din1_WIDTH => 44,
        dout_WIDTH => 93)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_272_p0,
        din1 => grp_fu_272_p1,
        ce => grp_fu_272_ce,
        dout => grp_fu_272_p2);

    mul_50ns_50ns_99_5_0_U57 : component LSTM_Top_mul_50ns_50ns_99_5_0
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 50,
        dout_WIDTH => 99)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_276_p0,
        din1 => grp_fu_276_p1,
        ce => grp_fu_276_ce,
        dout => grp_fu_276_p2);

    sparsemux_9_3_64_1_0_U58 : component LSTM_Top_sparsemux_9_3_64_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 64,
        CASE1 => "010",
        din1_WIDTH => 64,
        CASE2 => "001",
        din2_WIDTH => 64,
        CASE3 => "000",
        din3_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 3,
        dout_WIDTH => 64)
    port map (
        din0 => retval_1_fu_1069_p2,
        din1 => retval_1_fu_1069_p4,
        din2 => ap_const_lv64_0,
        din3 => retval_1_fu_1069_p8,
        def => retval_1_fu_1069_p9,
        sel => retval_1_fu_1069_p10,
        dout => retval_1_fu_1069_p11);

    mac_muladd_16s_15ns_19s_31_4_0_U59 : component LSTM_Top_mac_muladd_16s_15ns_19s_31_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 19,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => m_fix_hi_fu_457_p4,
        din1 => grp_fu_1093_p1,
        din2 => shl_ln_fu_496_p3,
        ce => grp_fu_1093_ce,
        dout => grp_fu_1093_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                Z2_reg_1224 <= sub_ln255_fu_593_p2(50 downto 43);
                Z2_reg_1224_pp0_iter11_reg <= Z2_reg_1224;
                Z2_reg_1224_pp0_iter12_reg <= Z2_reg_1224_pp0_iter11_reg;
                Z2_reg_1224_pp0_iter13_reg <= Z2_reg_1224_pp0_iter12_reg;
                Z2_reg_1224_pp0_iter14_reg <= Z2_reg_1224_pp0_iter13_reg;
                Z2_reg_1224_pp0_iter15_reg <= Z2_reg_1224_pp0_iter14_reg;
                Z2_reg_1224_pp0_iter16_reg <= Z2_reg_1224_pp0_iter15_reg;
                Z2_reg_1224_pp0_iter17_reg <= Z2_reg_1224_pp0_iter16_reg;
                Z2_reg_1224_pp0_iter18_reg <= Z2_reg_1224_pp0_iter17_reg;
                Z2_reg_1224_pp0_iter19_reg <= Z2_reg_1224_pp0_iter18_reg;
                Z2_reg_1224_pp0_iter20_reg <= Z2_reg_1224_pp0_iter19_reg;
                Z3_reg_1231 <= sub_ln255_fu_593_p2(42 downto 35);
                Z3_reg_1231_pp0_iter11_reg <= Z3_reg_1231;
                Z4_reg_1236 <= Z4_fu_628_p1;
                add_ln297_reg_1344 <= add_ln297_fu_828_p2;
                ashr_ln230_reg_1187 <= ashr_ln230_fu_491_p2;
                e_frac_2_reg_1122 <= e_frac_2_fu_362_p3;
                es_sign_reg_1104 <= data_fu_280_p1(63 downto 63);
                es_sign_reg_1104_pp0_iter10_reg <= es_sign_reg_1104_pp0_iter9_reg;
                es_sign_reg_1104_pp0_iter11_reg <= es_sign_reg_1104_pp0_iter10_reg;
                es_sign_reg_1104_pp0_iter12_reg <= es_sign_reg_1104_pp0_iter11_reg;
                es_sign_reg_1104_pp0_iter13_reg <= es_sign_reg_1104_pp0_iter12_reg;
                es_sign_reg_1104_pp0_iter14_reg <= es_sign_reg_1104_pp0_iter13_reg;
                es_sign_reg_1104_pp0_iter15_reg <= es_sign_reg_1104_pp0_iter14_reg;
                es_sign_reg_1104_pp0_iter16_reg <= es_sign_reg_1104_pp0_iter15_reg;
                es_sign_reg_1104_pp0_iter17_reg <= es_sign_reg_1104_pp0_iter16_reg;
                es_sign_reg_1104_pp0_iter18_reg <= es_sign_reg_1104_pp0_iter17_reg;
                es_sign_reg_1104_pp0_iter19_reg <= es_sign_reg_1104_pp0_iter18_reg;
                es_sign_reg_1104_pp0_iter1_reg <= es_sign_reg_1104;
                es_sign_reg_1104_pp0_iter20_reg <= es_sign_reg_1104_pp0_iter19_reg;
                es_sign_reg_1104_pp0_iter21_reg <= es_sign_reg_1104_pp0_iter20_reg;
                es_sign_reg_1104_pp0_iter22_reg <= es_sign_reg_1104_pp0_iter21_reg;
                es_sign_reg_1104_pp0_iter23_reg <= es_sign_reg_1104_pp0_iter22_reg;
                es_sign_reg_1104_pp0_iter24_reg <= es_sign_reg_1104_pp0_iter23_reg;
                es_sign_reg_1104_pp0_iter25_reg <= es_sign_reg_1104_pp0_iter24_reg;
                es_sign_reg_1104_pp0_iter26_reg <= es_sign_reg_1104_pp0_iter25_reg;
                es_sign_reg_1104_pp0_iter27_reg <= es_sign_reg_1104_pp0_iter26_reg;
                es_sign_reg_1104_pp0_iter2_reg <= es_sign_reg_1104_pp0_iter1_reg;
                es_sign_reg_1104_pp0_iter3_reg <= es_sign_reg_1104_pp0_iter2_reg;
                es_sign_reg_1104_pp0_iter4_reg <= es_sign_reg_1104_pp0_iter3_reg;
                es_sign_reg_1104_pp0_iter5_reg <= es_sign_reg_1104_pp0_iter4_reg;
                es_sign_reg_1104_pp0_iter6_reg <= es_sign_reg_1104_pp0_iter5_reg;
                es_sign_reg_1104_pp0_iter7_reg <= es_sign_reg_1104_pp0_iter6_reg;
                es_sign_reg_1104_pp0_iter8_reg <= es_sign_reg_1104_pp0_iter7_reg;
                es_sign_reg_1104_pp0_iter9_reg <= es_sign_reg_1104_pp0_iter8_reg;
                exp_Z1P_m_1_reg_1324 <= exp_Z1P_m_1_l_fu_794_p2(51 downto 2);
                exp_Z1_hi_reg_1329 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0(57 downto 8);
                exp_Z1_reg_1319 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0;
                exp_Z1_reg_1319_pp0_iter22_reg <= exp_Z1_reg_1319;
                exp_Z1_reg_1319_pp0_iter23_reg <= exp_Z1_reg_1319_pp0_iter22_reg;
                exp_Z1_reg_1319_pp0_iter24_reg <= exp_Z1_reg_1319_pp0_iter23_reg;
                exp_Z1_reg_1319_pp0_iter25_reg <= exp_Z1_reg_1319_pp0_iter24_reg;
                exp_Z2P_m_1_reg_1287 <= exp_Z2P_m_1_fu_721_p2;
                exp_Z2P_m_1_reg_1287_pp0_iter16_reg <= exp_Z2P_m_1_reg_1287;
                exp_Z2P_m_1_reg_1287_pp0_iter17_reg <= exp_Z2P_m_1_reg_1287_pp0_iter16_reg;
                exp_Z2P_m_1_reg_1287_pp0_iter18_reg <= exp_Z2P_m_1_reg_1287_pp0_iter17_reg;
                exp_Z2P_m_1_reg_1287_pp0_iter19_reg <= exp_Z2P_m_1_reg_1287_pp0_iter18_reg;
                exp_Z2P_m_1_reg_1287_pp0_iter20_reg <= exp_Z2P_m_1_reg_1287_pp0_iter19_reg;
                    exp_Z3_m_1_reg_1262(25 downto 0) <= exp_Z3_m_1_fu_675_p4(25 downto 0);    exp_Z3_m_1_reg_1262(42 downto 35) <= exp_Z3_m_1_fu_675_p4(42 downto 35);
                    exp_Z3_m_1_reg_1262_pp0_iter13_reg(25 downto 0) <= exp_Z3_m_1_reg_1262(25 downto 0);    exp_Z3_m_1_reg_1262_pp0_iter13_reg(42 downto 35) <= exp_Z3_m_1_reg_1262(42 downto 35);
                    exp_Z3_m_1_reg_1262_pp0_iter14_reg(25 downto 0) <= exp_Z3_m_1_reg_1262_pp0_iter13_reg(25 downto 0);    exp_Z3_m_1_reg_1262_pp0_iter14_reg(42 downto 35) <= exp_Z3_m_1_reg_1262_pp0_iter13_reg(42 downto 35);
                exp_Z4_m_1_reg_1251 <= exp_Z4_m_1_fu_669_p2;
                exp_Z4_m_1_reg_1251_pp0_iter12_reg <= exp_Z4_m_1_reg_1251;
                exp_Z4_m_1_reg_1251_pp0_iter13_reg <= exp_Z4_m_1_reg_1251_pp0_iter12_reg;
                exp_Z4_m_1_reg_1251_pp0_iter14_reg <= exp_Z4_m_1_reg_1251_pp0_iter13_reg;
                f_Z3_reg_1257 <= table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
                icmp_ln309_1_reg_1354 <= icmp_ln309_1_fu_879_p2;
                icmp_ln309_2_reg_1197 <= icmp_ln309_2_fu_520_p2;
                icmp_ln309_2_reg_1197_pp0_iter10_reg <= icmp_ln309_2_reg_1197_pp0_iter9_reg;
                icmp_ln309_2_reg_1197_pp0_iter11_reg <= icmp_ln309_2_reg_1197_pp0_iter10_reg;
                icmp_ln309_2_reg_1197_pp0_iter12_reg <= icmp_ln309_2_reg_1197_pp0_iter11_reg;
                icmp_ln309_2_reg_1197_pp0_iter13_reg <= icmp_ln309_2_reg_1197_pp0_iter12_reg;
                icmp_ln309_2_reg_1197_pp0_iter14_reg <= icmp_ln309_2_reg_1197_pp0_iter13_reg;
                icmp_ln309_2_reg_1197_pp0_iter15_reg <= icmp_ln309_2_reg_1197_pp0_iter14_reg;
                icmp_ln309_2_reg_1197_pp0_iter16_reg <= icmp_ln309_2_reg_1197_pp0_iter15_reg;
                icmp_ln309_2_reg_1197_pp0_iter17_reg <= icmp_ln309_2_reg_1197_pp0_iter16_reg;
                icmp_ln309_2_reg_1197_pp0_iter18_reg <= icmp_ln309_2_reg_1197_pp0_iter17_reg;
                icmp_ln309_2_reg_1197_pp0_iter19_reg <= icmp_ln309_2_reg_1197_pp0_iter18_reg;
                icmp_ln309_2_reg_1197_pp0_iter20_reg <= icmp_ln309_2_reg_1197_pp0_iter19_reg;
                icmp_ln309_2_reg_1197_pp0_iter21_reg <= icmp_ln309_2_reg_1197_pp0_iter20_reg;
                icmp_ln309_2_reg_1197_pp0_iter22_reg <= icmp_ln309_2_reg_1197_pp0_iter21_reg;
                icmp_ln309_2_reg_1197_pp0_iter23_reg <= icmp_ln309_2_reg_1197_pp0_iter22_reg;
                icmp_ln309_2_reg_1197_pp0_iter24_reg <= icmp_ln309_2_reg_1197_pp0_iter23_reg;
                icmp_ln309_2_reg_1197_pp0_iter25_reg <= icmp_ln309_2_reg_1197_pp0_iter24_reg;
                icmp_ln309_2_reg_1197_pp0_iter26_reg <= icmp_ln309_2_reg_1197_pp0_iter25_reg;
                icmp_ln309_2_reg_1197_pp0_iter27_reg <= icmp_ln309_2_reg_1197_pp0_iter26_reg;
                icmp_ln309_2_reg_1197_pp0_iter4_reg <= icmp_ln309_2_reg_1197;
                icmp_ln309_2_reg_1197_pp0_iter5_reg <= icmp_ln309_2_reg_1197_pp0_iter4_reg;
                icmp_ln309_2_reg_1197_pp0_iter6_reg <= icmp_ln309_2_reg_1197_pp0_iter5_reg;
                icmp_ln309_2_reg_1197_pp0_iter7_reg <= icmp_ln309_2_reg_1197_pp0_iter6_reg;
                icmp_ln309_2_reg_1197_pp0_iter8_reg <= icmp_ln309_2_reg_1197_pp0_iter7_reg;
                icmp_ln309_2_reg_1197_pp0_iter9_reg <= icmp_ln309_2_reg_1197_pp0_iter8_reg;
                icmp_ln309_reg_1138 <= icmp_ln309_fu_396_p2;
                icmp_ln309_reg_1138_pp0_iter10_reg <= icmp_ln309_reg_1138_pp0_iter9_reg;
                icmp_ln309_reg_1138_pp0_iter11_reg <= icmp_ln309_reg_1138_pp0_iter10_reg;
                icmp_ln309_reg_1138_pp0_iter12_reg <= icmp_ln309_reg_1138_pp0_iter11_reg;
                icmp_ln309_reg_1138_pp0_iter13_reg <= icmp_ln309_reg_1138_pp0_iter12_reg;
                icmp_ln309_reg_1138_pp0_iter14_reg <= icmp_ln309_reg_1138_pp0_iter13_reg;
                icmp_ln309_reg_1138_pp0_iter15_reg <= icmp_ln309_reg_1138_pp0_iter14_reg;
                icmp_ln309_reg_1138_pp0_iter16_reg <= icmp_ln309_reg_1138_pp0_iter15_reg;
                icmp_ln309_reg_1138_pp0_iter17_reg <= icmp_ln309_reg_1138_pp0_iter16_reg;
                icmp_ln309_reg_1138_pp0_iter18_reg <= icmp_ln309_reg_1138_pp0_iter17_reg;
                icmp_ln309_reg_1138_pp0_iter19_reg <= icmp_ln309_reg_1138_pp0_iter18_reg;
                icmp_ln309_reg_1138_pp0_iter1_reg <= icmp_ln309_reg_1138;
                icmp_ln309_reg_1138_pp0_iter20_reg <= icmp_ln309_reg_1138_pp0_iter19_reg;
                icmp_ln309_reg_1138_pp0_iter21_reg <= icmp_ln309_reg_1138_pp0_iter20_reg;
                icmp_ln309_reg_1138_pp0_iter22_reg <= icmp_ln309_reg_1138_pp0_iter21_reg;
                icmp_ln309_reg_1138_pp0_iter23_reg <= icmp_ln309_reg_1138_pp0_iter22_reg;
                icmp_ln309_reg_1138_pp0_iter24_reg <= icmp_ln309_reg_1138_pp0_iter23_reg;
                icmp_ln309_reg_1138_pp0_iter25_reg <= icmp_ln309_reg_1138_pp0_iter24_reg;
                icmp_ln309_reg_1138_pp0_iter26_reg <= icmp_ln309_reg_1138_pp0_iter25_reg;
                icmp_ln309_reg_1138_pp0_iter27_reg <= icmp_ln309_reg_1138_pp0_iter26_reg;
                icmp_ln309_reg_1138_pp0_iter2_reg <= icmp_ln309_reg_1138_pp0_iter1_reg;
                icmp_ln309_reg_1138_pp0_iter3_reg <= icmp_ln309_reg_1138_pp0_iter2_reg;
                icmp_ln309_reg_1138_pp0_iter4_reg <= icmp_ln309_reg_1138_pp0_iter3_reg;
                icmp_ln309_reg_1138_pp0_iter5_reg <= icmp_ln309_reg_1138_pp0_iter4_reg;
                icmp_ln309_reg_1138_pp0_iter6_reg <= icmp_ln309_reg_1138_pp0_iter5_reg;
                icmp_ln309_reg_1138_pp0_iter7_reg <= icmp_ln309_reg_1138_pp0_iter6_reg;
                icmp_ln309_reg_1138_pp0_iter8_reg <= icmp_ln309_reg_1138_pp0_iter7_reg;
                icmp_ln309_reg_1138_pp0_iter9_reg <= icmp_ln309_reg_1138_pp0_iter8_reg;
                icmp_ln326_reg_1361 <= icmp_ln326_fu_885_p2;
                m_diff_hi_reg_1219 <= sub_ln255_fu_593_p2(58 downto 51);
                m_diff_hi_reg_1219_pp0_iter11_reg <= m_diff_hi_reg_1219;
                m_diff_hi_reg_1219_pp0_iter12_reg <= m_diff_hi_reg_1219_pp0_iter11_reg;
                m_diff_hi_reg_1219_pp0_iter13_reg <= m_diff_hi_reg_1219_pp0_iter12_reg;
                m_diff_hi_reg_1219_pp0_iter14_reg <= m_diff_hi_reg_1219_pp0_iter13_reg;
                m_diff_hi_reg_1219_pp0_iter15_reg <= m_diff_hi_reg_1219_pp0_iter14_reg;
                m_diff_hi_reg_1219_pp0_iter16_reg <= m_diff_hi_reg_1219_pp0_iter15_reg;
                m_diff_hi_reg_1219_pp0_iter17_reg <= m_diff_hi_reg_1219_pp0_iter16_reg;
                m_diff_hi_reg_1219_pp0_iter18_reg <= m_diff_hi_reg_1219_pp0_iter17_reg;
                m_diff_hi_reg_1219_pp0_iter19_reg <= m_diff_hi_reg_1219_pp0_iter18_reg;
                m_fix_l_reg_1161 <= m_fix_fu_440_p3(70 downto 7);
                mul_ln297_reg_1349 <= grp_fu_276_p2;
                r_exp_reg_1202 <= r_exp_fu_564_p3;
                r_exp_reg_1202_pp0_iter10_reg <= r_exp_reg_1202_pp0_iter9_reg;
                r_exp_reg_1202_pp0_iter11_reg <= r_exp_reg_1202_pp0_iter10_reg;
                r_exp_reg_1202_pp0_iter12_reg <= r_exp_reg_1202_pp0_iter11_reg;
                r_exp_reg_1202_pp0_iter13_reg <= r_exp_reg_1202_pp0_iter12_reg;
                r_exp_reg_1202_pp0_iter14_reg <= r_exp_reg_1202_pp0_iter13_reg;
                r_exp_reg_1202_pp0_iter15_reg <= r_exp_reg_1202_pp0_iter14_reg;
                r_exp_reg_1202_pp0_iter16_reg <= r_exp_reg_1202_pp0_iter15_reg;
                r_exp_reg_1202_pp0_iter17_reg <= r_exp_reg_1202_pp0_iter16_reg;
                r_exp_reg_1202_pp0_iter18_reg <= r_exp_reg_1202_pp0_iter17_reg;
                r_exp_reg_1202_pp0_iter19_reg <= r_exp_reg_1202_pp0_iter18_reg;
                r_exp_reg_1202_pp0_iter20_reg <= r_exp_reg_1202_pp0_iter19_reg;
                r_exp_reg_1202_pp0_iter21_reg <= r_exp_reg_1202_pp0_iter20_reg;
                r_exp_reg_1202_pp0_iter22_reg <= r_exp_reg_1202_pp0_iter21_reg;
                r_exp_reg_1202_pp0_iter23_reg <= r_exp_reg_1202_pp0_iter22_reg;
                r_exp_reg_1202_pp0_iter24_reg <= r_exp_reg_1202_pp0_iter23_reg;
                r_exp_reg_1202_pp0_iter25_reg <= r_exp_reg_1202_pp0_iter24_reg;
                r_exp_reg_1202_pp0_iter26_reg <= r_exp_reg_1202_pp0_iter25_reg;
                r_exp_reg_1202_pp0_iter5_reg <= r_exp_reg_1202;
                r_exp_reg_1202_pp0_iter6_reg <= r_exp_reg_1202_pp0_iter5_reg;
                r_exp_reg_1202_pp0_iter7_reg <= r_exp_reg_1202_pp0_iter6_reg;
                r_exp_reg_1202_pp0_iter8_reg <= r_exp_reg_1202_pp0_iter7_reg;
                r_exp_reg_1202_pp0_iter9_reg <= r_exp_reg_1202_pp0_iter8_reg;
                select_ln229_reg_1133 <= select_ln229_fu_388_p3;
                select_ln303_reg_1371 <= select_ln303_fu_915_p3;
                    sext_ln227_reg_1151(70 downto 7) <= sext_ln227_fu_417_p1(70 downto 7);
                    sext_ln227_reg_1151_pp0_iter2_reg(70 downto 7) <= sext_ln227_reg_1151(70 downto 7);
                sext_ln229_1_reg_1156 <= sext_ln229_1_fu_421_p1;
                shl_ln230_reg_1182 <= shl_ln230_fu_486_p2;
                tmp_10_reg_1146 <= e_frac_2_fu_362_p3(53 downto 53);
                tmp_10_reg_1146_pp0_iter10_reg <= tmp_10_reg_1146_pp0_iter9_reg;
                tmp_10_reg_1146_pp0_iter11_reg <= tmp_10_reg_1146_pp0_iter10_reg;
                tmp_10_reg_1146_pp0_iter12_reg <= tmp_10_reg_1146_pp0_iter11_reg;
                tmp_10_reg_1146_pp0_iter13_reg <= tmp_10_reg_1146_pp0_iter12_reg;
                tmp_10_reg_1146_pp0_iter14_reg <= tmp_10_reg_1146_pp0_iter13_reg;
                tmp_10_reg_1146_pp0_iter15_reg <= tmp_10_reg_1146_pp0_iter14_reg;
                tmp_10_reg_1146_pp0_iter16_reg <= tmp_10_reg_1146_pp0_iter15_reg;
                tmp_10_reg_1146_pp0_iter17_reg <= tmp_10_reg_1146_pp0_iter16_reg;
                tmp_10_reg_1146_pp0_iter18_reg <= tmp_10_reg_1146_pp0_iter17_reg;
                tmp_10_reg_1146_pp0_iter19_reg <= tmp_10_reg_1146_pp0_iter18_reg;
                tmp_10_reg_1146_pp0_iter1_reg <= tmp_10_reg_1146;
                tmp_10_reg_1146_pp0_iter20_reg <= tmp_10_reg_1146_pp0_iter19_reg;
                tmp_10_reg_1146_pp0_iter21_reg <= tmp_10_reg_1146_pp0_iter20_reg;
                tmp_10_reg_1146_pp0_iter22_reg <= tmp_10_reg_1146_pp0_iter21_reg;
                tmp_10_reg_1146_pp0_iter23_reg <= tmp_10_reg_1146_pp0_iter22_reg;
                tmp_10_reg_1146_pp0_iter24_reg <= tmp_10_reg_1146_pp0_iter23_reg;
                tmp_10_reg_1146_pp0_iter25_reg <= tmp_10_reg_1146_pp0_iter24_reg;
                tmp_10_reg_1146_pp0_iter26_reg <= tmp_10_reg_1146_pp0_iter25_reg;
                tmp_10_reg_1146_pp0_iter27_reg <= tmp_10_reg_1146_pp0_iter26_reg;
                tmp_10_reg_1146_pp0_iter2_reg <= tmp_10_reg_1146_pp0_iter1_reg;
                tmp_10_reg_1146_pp0_iter3_reg <= tmp_10_reg_1146_pp0_iter2_reg;
                tmp_10_reg_1146_pp0_iter4_reg <= tmp_10_reg_1146_pp0_iter3_reg;
                tmp_10_reg_1146_pp0_iter5_reg <= tmp_10_reg_1146_pp0_iter4_reg;
                tmp_10_reg_1146_pp0_iter6_reg <= tmp_10_reg_1146_pp0_iter5_reg;
                tmp_10_reg_1146_pp0_iter7_reg <= tmp_10_reg_1146_pp0_iter6_reg;
                tmp_10_reg_1146_pp0_iter8_reg <= tmp_10_reg_1146_pp0_iter7_reg;
                tmp_10_reg_1146_pp0_iter9_reg <= tmp_10_reg_1146_pp0_iter8_reg;
                tmp_1_reg_1293 <= table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0(41 downto 2);
                tmp_1_reg_1293_pp0_iter16_reg <= tmp_1_reg_1293;
                tmp_1_reg_1293_pp0_iter17_reg <= tmp_1_reg_1293_pp0_iter16_reg;
                tmp_1_reg_1293_pp0_iter18_reg <= tmp_1_reg_1293_pp0_iter17_reg;
                tmp_1_reg_1293_pp0_iter19_reg <= tmp_1_reg_1293_pp0_iter18_reg;
                tmp_1_reg_1293_pp0_iter20_reg <= tmp_1_reg_1293_pp0_iter19_reg;
                tmp_2_reg_1167 <= m_fix_fu_440_p3(70 downto 70);
                tmp_2_reg_1167_pp0_iter2_reg <= tmp_2_reg_1167;
                tmp_4_reg_1314 <= grp_fu_272_p2(92 downto 57);
                tmp_8_reg_1214 <= grp_fu_263_p2(70 downto 13);
                tmp_reg_1127 <= m_exp_fu_338_p2(11 downto 11);
                tmp_reg_1127_pp0_iter1_reg <= tmp_reg_1127;
                tmp_reg_1127_pp0_iter2_reg <= tmp_reg_1127_pp0_iter1_reg;
                tmp_s_reg_1277 <= grp_fu_268_p2(78 downto 59);
                trunc_ln255_reg_1177 <= trunc_ln255_fu_479_p1;
                trunc_ln255_reg_1177_pp0_iter2_reg <= trunc_ln255_reg_1177;
                trunc_ln255_reg_1177_pp0_iter3_reg <= trunc_ln255_reg_1177_pp0_iter2_reg;
                trunc_ln255_reg_1177_pp0_iter4_reg <= trunc_ln255_reg_1177_pp0_iter3_reg;
                trunc_ln255_reg_1177_pp0_iter5_reg <= trunc_ln255_reg_1177_pp0_iter4_reg;
                trunc_ln255_reg_1177_pp0_iter6_reg <= trunc_ln255_reg_1177_pp0_iter5_reg;
                trunc_ln255_reg_1177_pp0_iter7_reg <= trunc_ln255_reg_1177_pp0_iter6_reg;
                trunc_ln255_reg_1177_pp0_iter8_reg <= trunc_ln255_reg_1177_pp0_iter7_reg;
                trunc_ln255_reg_1177_pp0_iter9_reg <= trunc_ln255_reg_1177_pp0_iter8_reg;
                trunc_ln336_reg_1366 <= trunc_ln336_fu_891_p1;
                x_is_NaN_reg_1109 <= x_is_NaN_fu_316_p2;
                x_is_NaN_reg_1109_pp0_iter10_reg <= x_is_NaN_reg_1109_pp0_iter9_reg;
                x_is_NaN_reg_1109_pp0_iter11_reg <= x_is_NaN_reg_1109_pp0_iter10_reg;
                x_is_NaN_reg_1109_pp0_iter12_reg <= x_is_NaN_reg_1109_pp0_iter11_reg;
                x_is_NaN_reg_1109_pp0_iter13_reg <= x_is_NaN_reg_1109_pp0_iter12_reg;
                x_is_NaN_reg_1109_pp0_iter14_reg <= x_is_NaN_reg_1109_pp0_iter13_reg;
                x_is_NaN_reg_1109_pp0_iter15_reg <= x_is_NaN_reg_1109_pp0_iter14_reg;
                x_is_NaN_reg_1109_pp0_iter16_reg <= x_is_NaN_reg_1109_pp0_iter15_reg;
                x_is_NaN_reg_1109_pp0_iter17_reg <= x_is_NaN_reg_1109_pp0_iter16_reg;
                x_is_NaN_reg_1109_pp0_iter18_reg <= x_is_NaN_reg_1109_pp0_iter17_reg;
                x_is_NaN_reg_1109_pp0_iter19_reg <= x_is_NaN_reg_1109_pp0_iter18_reg;
                x_is_NaN_reg_1109_pp0_iter1_reg <= x_is_NaN_reg_1109;
                x_is_NaN_reg_1109_pp0_iter20_reg <= x_is_NaN_reg_1109_pp0_iter19_reg;
                x_is_NaN_reg_1109_pp0_iter21_reg <= x_is_NaN_reg_1109_pp0_iter20_reg;
                x_is_NaN_reg_1109_pp0_iter22_reg <= x_is_NaN_reg_1109_pp0_iter21_reg;
                x_is_NaN_reg_1109_pp0_iter23_reg <= x_is_NaN_reg_1109_pp0_iter22_reg;
                x_is_NaN_reg_1109_pp0_iter24_reg <= x_is_NaN_reg_1109_pp0_iter23_reg;
                x_is_NaN_reg_1109_pp0_iter25_reg <= x_is_NaN_reg_1109_pp0_iter24_reg;
                x_is_NaN_reg_1109_pp0_iter26_reg <= x_is_NaN_reg_1109_pp0_iter25_reg;
                x_is_NaN_reg_1109_pp0_iter27_reg <= x_is_NaN_reg_1109_pp0_iter26_reg;
                x_is_NaN_reg_1109_pp0_iter2_reg <= x_is_NaN_reg_1109_pp0_iter1_reg;
                x_is_NaN_reg_1109_pp0_iter3_reg <= x_is_NaN_reg_1109_pp0_iter2_reg;
                x_is_NaN_reg_1109_pp0_iter4_reg <= x_is_NaN_reg_1109_pp0_iter3_reg;
                x_is_NaN_reg_1109_pp0_iter5_reg <= x_is_NaN_reg_1109_pp0_iter4_reg;
                x_is_NaN_reg_1109_pp0_iter6_reg <= x_is_NaN_reg_1109_pp0_iter5_reg;
                x_is_NaN_reg_1109_pp0_iter7_reg <= x_is_NaN_reg_1109_pp0_iter6_reg;
                x_is_NaN_reg_1109_pp0_iter8_reg <= x_is_NaN_reg_1109_pp0_iter7_reg;
                x_is_NaN_reg_1109_pp0_iter9_reg <= x_is_NaN_reg_1109_pp0_iter8_reg;
                x_is_inf_reg_1116 <= x_is_inf_fu_328_p2;
                x_is_inf_reg_1116_pp0_iter10_reg <= x_is_inf_reg_1116_pp0_iter9_reg;
                x_is_inf_reg_1116_pp0_iter11_reg <= x_is_inf_reg_1116_pp0_iter10_reg;
                x_is_inf_reg_1116_pp0_iter12_reg <= x_is_inf_reg_1116_pp0_iter11_reg;
                x_is_inf_reg_1116_pp0_iter13_reg <= x_is_inf_reg_1116_pp0_iter12_reg;
                x_is_inf_reg_1116_pp0_iter14_reg <= x_is_inf_reg_1116_pp0_iter13_reg;
                x_is_inf_reg_1116_pp0_iter15_reg <= x_is_inf_reg_1116_pp0_iter14_reg;
                x_is_inf_reg_1116_pp0_iter16_reg <= x_is_inf_reg_1116_pp0_iter15_reg;
                x_is_inf_reg_1116_pp0_iter17_reg <= x_is_inf_reg_1116_pp0_iter16_reg;
                x_is_inf_reg_1116_pp0_iter18_reg <= x_is_inf_reg_1116_pp0_iter17_reg;
                x_is_inf_reg_1116_pp0_iter19_reg <= x_is_inf_reg_1116_pp0_iter18_reg;
                x_is_inf_reg_1116_pp0_iter1_reg <= x_is_inf_reg_1116;
                x_is_inf_reg_1116_pp0_iter20_reg <= x_is_inf_reg_1116_pp0_iter19_reg;
                x_is_inf_reg_1116_pp0_iter21_reg <= x_is_inf_reg_1116_pp0_iter20_reg;
                x_is_inf_reg_1116_pp0_iter22_reg <= x_is_inf_reg_1116_pp0_iter21_reg;
                x_is_inf_reg_1116_pp0_iter23_reg <= x_is_inf_reg_1116_pp0_iter22_reg;
                x_is_inf_reg_1116_pp0_iter24_reg <= x_is_inf_reg_1116_pp0_iter23_reg;
                x_is_inf_reg_1116_pp0_iter25_reg <= x_is_inf_reg_1116_pp0_iter24_reg;
                x_is_inf_reg_1116_pp0_iter26_reg <= x_is_inf_reg_1116_pp0_iter25_reg;
                x_is_inf_reg_1116_pp0_iter27_reg <= x_is_inf_reg_1116_pp0_iter26_reg;
                x_is_inf_reg_1116_pp0_iter2_reg <= x_is_inf_reg_1116_pp0_iter1_reg;
                x_is_inf_reg_1116_pp0_iter3_reg <= x_is_inf_reg_1116_pp0_iter2_reg;
                x_is_inf_reg_1116_pp0_iter4_reg <= x_is_inf_reg_1116_pp0_iter3_reg;
                x_is_inf_reg_1116_pp0_iter5_reg <= x_is_inf_reg_1116_pp0_iter4_reg;
                x_is_inf_reg_1116_pp0_iter6_reg <= x_is_inf_reg_1116_pp0_iter5_reg;
                x_is_inf_reg_1116_pp0_iter7_reg <= x_is_inf_reg_1116_pp0_iter6_reg;
                x_is_inf_reg_1116_pp0_iter8_reg <= x_is_inf_reg_1116_pp0_iter7_reg;
                x_is_inf_reg_1116_pp0_iter9_reg <= x_is_inf_reg_1116_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= retval_1_fu_1069_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    sext_ln227_reg_1151(6 downto 0) <= "0000000";
    sext_ln227_reg_1151_pp0_iter2_reg(6 downto 0) <= "0000000";
    exp_Z3_m_1_reg_1262(34 downto 26) <= "000000000";
    exp_Z3_m_1_reg_1262_pp0_iter13_reg(34 downto 26) <= "000000000";
    exp_Z3_m_1_reg_1262_pp0_iter14_reg(34 downto 26) <= "000000000";
    Z3_fu_618_p4 <= sub_ln255_fu_593_p2(42 downto 35);
    Z4_fu_628_p1 <= sub_ln255_fu_593_p2(35 - 1 downto 0);
    Z4_ind_fu_632_p4 <= sub_ln255_fu_593_p2(34 downto 27);
    add_ln126_fu_712_p2 <= std_logic_vector(unsigned(exp_Z4_m_1_reg_1251_pp0_iter14_reg) + unsigned(zext_ln126_1_fu_709_p1));
    add_ln145_fu_785_p2 <= std_logic_vector(unsigned(exp_Z2P_m_1_reg_1287_pp0_iter20_reg) + unsigned(zext_ln145_2_fu_782_p1));
    add_ln243_1_fu_550_p2 <= std_logic_vector(unsigned(tmp_1_cast_fu_525_p4) + unsigned(ap_const_lv13_1));
    add_ln297_1_fu_843_p2 <= std_logic_vector(unsigned(shl_ln1_fu_833_p3) + unsigned(zext_ln297_2_fu_840_p1));
    add_ln297_fu_828_p2 <= std_logic_vector(unsigned(exp_Z1_reg_1319_pp0_iter25_reg) + unsigned(ap_const_lv58_10));
    and_ln1_fu_768_p5 <= (((Z2_reg_1224_pp0_iter20_reg & ap_const_lv1_0) & tmp_1_reg_1293_pp0_iter20_reg) & ap_const_lv2_0);
    and_ln309_1_fu_998_p2 <= (xor_ln309_fu_993_p2 and icmp_ln309_1_reg_1354);
    and_ln309_2_fu_1015_p2 <= (xor_ln185_fu_1009_p2 and or_ln309_1_fu_1003_p2);
    and_ln309_3_fu_1027_p2 <= (xor_ln309_1_fu_1021_p2 and icmp_ln309_reg_1138_pp0_iter27_reg);
    and_ln309_4_fu_1048_p2 <= (xor_ln185_fu_1009_p2 and or_ln309_3_fu_1042_p2);
    and_ln309_5_fu_1054_p2 <= (icmp_ln326_reg_1361 and and_ln309_4_fu_1048_p2);
    and_ln309_fu_988_p2 <= (or_ln309_fu_957_p2 and icmp_ln309_reg_1138_pp0_iter27_reg);
    and_ln_fu_586_p3 <= (tmp_8_reg_1214 & ap_const_lv1_0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(retval_1_fu_1069_p11, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= retval_1_fu_1069_p11;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ashr_ln229_fu_428_p2 <= std_logic_vector(shift_right(signed(sext_ln227_fu_417_p1),to_integer(unsigned('0' & zext_ln229_fu_424_p1(31-1 downto 0)))));
    ashr_ln230_fu_491_p2 <= std_logic_vector(shift_right(signed(m_fix_l_reg_1161),to_integer(unsigned('0' & zext_ln230_fu_483_p1(31-1 downto 0)))));
    data_fu_280_p1 <= x_int_reg;
    e_frac_1_fu_356_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln221_fu_352_p1));
    e_frac_2_fu_362_p3 <= 
        e_frac_1_fu_356_p2 when (es_sign_fu_284_p3(0) = '1') else 
        zext_ln221_fu_352_p1;
    e_frac_fu_344_p3 <= (ap_const_lv1_1 & es_sig_fu_300_p1);
    es_exp_fu_292_p3 <= data_fu_280_p1(62 downto 52);
    es_sig_fu_300_p1 <= data_fu_280_p1(52 - 1 downto 0);
    es_sign_fu_284_p3 <= data_fu_280_p1(63 downto 63);
    exp_Z1P_m_1_l_fu_794_p2 <= std_logic_vector(unsigned(zext_ln145_1_fu_790_p1) + unsigned(zext_ln145_fu_778_p1));
    exp_Z2P_m_1_fu_721_p2 <= std_logic_vector(unsigned(zext_ln126_fu_717_p1) + unsigned(zext_ln120_fu_706_p1));
    exp_Z2_m_1_fu_737_p4 <= ((Z2_reg_1224_pp0_iter15_reg & ap_const_lv1_0) & tmp_1_reg_1293);
    exp_Z3_m_1_fu_675_p4 <= ((Z3_reg_1231_pp0_iter11_reg & ap_const_lv9_0) & f_Z3_reg_1257);
    exp_Z4_m_1_fu_669_p2 <= std_logic_vector(unsigned(zext_ln115_fu_662_p1) + unsigned(zext_ln115_1_fu_665_p1));
    f_Z4_fu_652_p4 <= table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1(25 downto 16);

    grp_fu_1093_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_1093_ce <= ap_const_logic_1;
        else 
            grp_fu_1093_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1093_p1 <= ap_const_lv31_5C55(15 - 1 downto 0);

    grp_fu_263_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_263_ce <= ap_const_logic_1;
        else 
            grp_fu_263_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_268_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_268_ce <= ap_const_logic_1;
        else 
            grp_fu_268_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_268_p0 <= grp_fu_268_p00(43 - 1 downto 0);
    grp_fu_268_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z3_m_1_fu_675_p4),79));
    grp_fu_268_p1 <= grp_fu_268_p10(36 - 1 downto 0);
    grp_fu_268_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z4_m_1_reg_1251),79));

    grp_fu_272_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_272_ce <= ap_const_logic_1;
        else 
            grp_fu_272_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_272_p0 <= grp_fu_272_p00(49 - 1 downto 0);
    grp_fu_272_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z2_m_1_fu_737_p4),93));
    grp_fu_272_p1 <= grp_fu_272_p10(44 - 1 downto 0);
    grp_fu_272_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z2P_m_1_reg_1287),93));

    grp_fu_276_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_276_ce <= ap_const_logic_1;
        else 
            grp_fu_276_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_276_p0 <= grp_fu_276_p00(50 - 1 downto 0);
    grp_fu_276_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1P_m_1_reg_1324),99));
    grp_fu_276_p1 <= grp_fu_276_p10(50 - 1 downto 0);
    grp_fu_276_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1_hi_reg_1329),99));
    icmp_ln18_1_fu_310_p2 <= "0" when (es_sig_fu_300_p1 = ap_const_lv52_0) else "1";
    icmp_ln18_2_fu_322_p2 <= "1" when (es_sig_fu_300_p1 = ap_const_lv52_0) else "0";
    icmp_ln18_fu_304_p2 <= "1" when (es_exp_fu_292_p3 = ap_const_lv11_7FF) else "0";
    icmp_ln243_fu_544_p2 <= "0" when (trunc_ln243_fu_541_p1 = ap_const_lv18_0) else "1";
    icmp_ln309_1_fu_879_p2 <= "1" when (signed(tmp_9_fu_869_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln309_2_fu_520_p2 <= "0" when (shl_ln2_fu_512_p3 = sext_ln227_reg_1151_pp0_iter2_reg) else "1";
    icmp_ln309_fu_396_p2 <= "1" when (signed(m_exp_fu_338_p2) > signed(ap_const_lv12_0)) else "0";
    icmp_ln326_fu_885_p2 <= "1" when (signed(r_exp_2_fu_862_p3) < signed(ap_const_lv13_1C02)) else "0";
    m_exp_fu_338_p2 <= std_logic_vector(unsigned(zext_ln486_fu_334_p1) + unsigned(ap_const_lv12_C01));
    m_fix_fu_440_p3 <= 
        ashr_ln229_fu_428_p2 when (tmp_reg_1127(0) = '1') else 
        shl_ln229_fu_434_p2;
    m_fix_hi_fu_457_p4 <= m_fix_fu_440_p3(70 downto 55);
    m_frac_l_fu_410_p3 <= (e_frac_2_reg_1122 & ap_const_lv7_0);
    or_ln185_1_fu_945_p2 <= (x_is_inf_reg_1116_pp0_iter27_reg or x_is_NaN_reg_1109_pp0_iter27_reg);
    or_ln185_fu_933_p2 <= (x_is_pinf_fu_928_p2 or x_is_NaN_reg_1109_pp0_iter27_reg);
    or_ln309_1_fu_1003_p2 <= (and_ln309_fu_988_p2 or and_ln309_1_fu_998_p2);
    or_ln309_2_fu_1032_p2 <= (icmp_ln309_reg_1138_pp0_iter27_reg or icmp_ln309_1_reg_1354);
    or_ln309_3_fu_1042_p2 <= (xor_ln309_2_fu_1036_p2 or and_ln309_3_fu_1027_p2);
    or_ln309_fu_957_p2 <= (icmp_ln309_2_reg_1197_pp0_iter27_reg or icmp_ln309_1_reg_1354);
    out_exp_fu_968_p2 <= std_logic_vector(unsigned(trunc_ln336_reg_1366) + unsigned(ap_const_lv11_3FF));
    r_exp_1_fu_857_p2 <= std_logic_vector(signed(r_exp_reg_1202_pp0_iter26_reg) + signed(ap_const_lv13_1FFF));
    r_exp_2_fu_862_p3 <= 
        r_exp_reg_1202_pp0_iter26_reg when (tmp_5_fu_849_p3(0) = '1') else 
        r_exp_1_fu_857_p2;
    r_exp_fu_564_p3 <= 
        select_ln243_fu_556_p3 when (tmp_3_fu_534_p3(0) = '1') else 
        tmp_1_cast_fu_525_p4;
    retval_1_fu_1069_p10 <= ((or_ln185_1_fu_945_p2 & and_ln309_2_fu_1015_p2) & and_ln309_5_fu_1054_p2);
    retval_1_fu_1069_p2 <= 
        select_ln185_fu_938_p3 when (or_ln185_fu_933_p2(0) = '1') else 
        ap_const_lv64_0;
    retval_1_fu_1069_p4 <= 
        ap_const_lv64_0 when (tmp_10_reg_1146_pp0_iter27_reg(0) = '1') else 
        ap_const_lv64_7FF0000000000000;
    retval_1_fu_1069_p8 <= zext_ln479_fu_980_p1;
    retval_1_fu_1069_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln185_fu_938_p3 <= 
        ap_const_lv64_7FFFFFFFFFFFFFFF when (x_is_NaN_reg_1109_pp0_iter27_reg(0) = '1') else 
        ap_const_lv64_7FF0000000000000;
    select_ln229_fu_388_p3 <= 
        sext_ln229_fu_384_p1 when (tmp_fu_370_p3(0) = '1') else 
        m_exp_fu_338_p2;
    select_ln230_fu_507_p3 <= 
        shl_ln230_reg_1182 when (tmp_reg_1127_pp0_iter2_reg(0) = '1') else 
        ashr_ln230_reg_1187;
    select_ln243_fu_556_p3 <= 
        add_ln243_1_fu_550_p2 when (icmp_ln243_fu_544_p2(0) = '1') else 
        tmp_1_cast_fu_525_p4;
    select_ln303_fu_915_p3 <= 
        tmp_6_fu_895_p4 when (tmp_5_fu_849_p3(0) = '1') else 
        tmp_7_fu_905_p4;
        sext_ln227_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_frac_l_fu_410_p3),71));

        sext_ln229_1_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln229_reg_1133),32));

        sext_ln229_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln229_fu_378_p2),12));

    shl_ln1_fu_833_p3 <= (add_ln297_reg_1344 & ap_const_lv49_0);
    shl_ln229_fu_434_p2 <= std_logic_vector(shift_left(unsigned(sext_ln227_fu_417_p1),to_integer(unsigned('0' & zext_ln229_fu_424_p1(31-1 downto 0)))));
    shl_ln230_fu_486_p2 <= std_logic_vector(shift_left(unsigned(m_fix_l_reg_1161),to_integer(unsigned('0' & zext_ln230_fu_483_p1(31-1 downto 0)))));
    shl_ln2_fu_512_p3 <= (select_ln230_fu_507_p3 & ap_const_lv7_0);
    shl_ln_fu_496_p3 <= (tmp_2_reg_1167_pp0_iter2_reg & ap_const_lv18_20000);
    sub_ln229_fu_378_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(es_exp_fu_292_p3));
    sub_ln255_fu_593_p2 <= std_logic_vector(unsigned(trunc_ln255_reg_1177_pp0_iter9_reg) - unsigned(and_ln_fu_586_p3));
    t_fu_973_p3 <= (out_exp_fu_968_p2 & select_ln303_reg_1371);
    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0 <= zext_ln292_fu_754_p1(8 - 1 downto 0);

    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local <= ap_const_logic_1;
        else 
            table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 <= zext_ln138_fu_702_p1(8 - 1 downto 0);

    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local <= ap_const_logic_1;
        else 
            table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 <= zext_ln119_fu_647_p1(8 - 1 downto 0);
    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1 <= zext_ln114_fu_642_p1(8 - 1 downto 0);

    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local <= ap_const_logic_1;
        else 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local <= ap_const_logic_1;
        else 
            table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_cast_fu_525_p4 <= grp_fu_1093_p3(30 downto 18);
    tmp_3_fu_534_p3 <= grp_fu_1093_p3(30 downto 30);
    tmp_5_fu_849_p3 <= add_ln297_1_fu_843_p2(106 downto 106);
    tmp_6_fu_895_p4 <= add_ln297_1_fu_843_p2(105 downto 54);
    tmp_7_fu_905_p4 <= add_ln297_1_fu_843_p2(104 downto 53);
    tmp_9_fu_869_p4 <= r_exp_2_fu_862_p3(12 downto 10);
    tmp_fu_370_p3 <= m_exp_fu_338_p2(11 downto 11);
    trunc_ln243_fu_541_p1 <= grp_fu_1093_p3(18 - 1 downto 0);
    trunc_ln255_fu_479_p1 <= m_fix_fu_440_p3(59 - 1 downto 0);
    trunc_ln336_fu_891_p1 <= r_exp_2_fu_862_p3(11 - 1 downto 0);
    x_is_NaN_fu_316_p2 <= (icmp_ln18_fu_304_p2 and icmp_ln18_1_fu_310_p2);
    x_is_inf_fu_328_p2 <= (icmp_ln18_fu_304_p2 and icmp_ln18_2_fu_322_p2);
    x_is_pinf_fu_928_p2 <= (xor_ln182_fu_923_p2 and x_is_inf_reg_1116_pp0_iter27_reg);
    xor_ln182_fu_923_p2 <= (es_sign_reg_1104_pp0_iter27_reg xor ap_const_lv1_1);
    xor_ln185_fu_1009_p2 <= (or_ln185_1_fu_945_p2 xor ap_const_lv1_1);
    xor_ln309_1_fu_1021_p2 <= (or_ln309_fu_957_p2 xor ap_const_lv1_1);
    xor_ln309_2_fu_1036_p2 <= (or_ln309_2_fu_1032_p2 xor ap_const_lv1_1);
    xor_ln309_fu_993_p2 <= (icmp_ln309_reg_1138_pp0_iter27_reg xor ap_const_lv1_1);
    zext_ln114_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z4_ind_fu_632_p4),64));
    zext_ln115_1_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_Z4_fu_652_p4),36));
    zext_ln115_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z4_reg_1236),36));
    zext_ln119_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z3_fu_618_p4),64));
    zext_ln120_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z3_m_1_reg_1262_pp0_iter14_reg),44));
    zext_ln126_1_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_1277),36));
    zext_ln126_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln126_fu_712_p2),44));
    zext_ln138_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z2_reg_1224_pp0_iter13_reg),64));
    zext_ln145_1_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln145_fu_785_p2),52));
    zext_ln145_2_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_1314),44));
    zext_ln145_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln1_fu_768_p5),52));
    zext_ln221_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_frac_fu_344_p3),54));
    zext_ln229_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln229_1_fu_421_p1),71));
    zext_ln230_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln229_1_reg_1156),64));
    zext_ln292_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_diff_hi_reg_1219_pp0_iter19_reg),64));
    zext_ln297_2_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln297_reg_1349),107));
    zext_ln479_fu_980_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_fu_973_p3),64));
    zext_ln486_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(es_exp_fu_292_p3),12));
end behav;
