// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module LSTM_Top_infer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        res_address0,
        res_ce0,
        res_we0,
        res_d0,
        res_address1,
        res_ce1,
        res_q1,
        grp_fu_114_p_din0,
        grp_fu_114_p_din1,
        grp_fu_114_p_dout0,
        grp_fu_114_p_ce
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [3:0] res_address0;
output   res_ce0;
output   res_we0;
output  [31:0] res_d0;
output  [3:0] res_address1;
output   res_ce1;
input  [31:0] res_q1;
output  [31:0] grp_fu_114_p_din0;
output  [31:0] grp_fu_114_p_din1;
input  [31:0] grp_fu_114_p_dout0;
output   grp_fu_114_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] res_address0;
reg res_ce0;
reg res_we0;
reg[31:0] res_d0;
reg[3:0] res_address1;
reg res_ce1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] gate_f_address0;
reg    gate_f_ce0;
reg    gate_f_we0;
reg   [31:0] gate_f_d0;
wire   [31:0] gate_f_q0;
reg    gate_f_ce1;
wire   [31:0] gate_f_q1;
reg   [6:0] gate_i_address0;
reg    gate_i_ce0;
reg    gate_i_we0;
reg   [31:0] gate_i_d0;
wire   [31:0] gate_i_q0;
reg    gate_i_ce1;
wire   [31:0] gate_i_q1;
reg   [6:0] stat_C_address0;
reg    stat_C_ce0;
reg    stat_C_we0;
reg   [31:0] stat_C_d0;
wire   [31:0] stat_C_q0;
reg    stat_C_ce1;
wire   [31:0] stat_C_q1;
reg   [6:0] C_t_address0;
reg    C_t_ce0;
reg    C_t_we0;
reg   [31:0] C_t_d0;
wire   [31:0] C_t_q0;
reg   [6:0] gate_o_address0;
reg    gate_o_ce0;
reg    gate_o_we0;
reg   [31:0] gate_o_d0;
wire   [31:0] gate_o_q0;
reg    gate_o_ce1;
wire   [31:0] gate_o_q1;
reg   [6:0] h_t_address0;
reg    h_t_ce0;
reg    h_t_we0;
reg   [31:0] h_t_d0;
wire   [31:0] h_t_q0;
wire    grp_infer_Pipeline_1_fu_76_ap_start;
wire    grp_infer_Pipeline_1_fu_76_ap_done;
wire    grp_infer_Pipeline_1_fu_76_ap_idle;
wire    grp_infer_Pipeline_1_fu_76_ap_ready;
wire   [6:0] grp_infer_Pipeline_1_fu_76_gate_f_address0;
wire    grp_infer_Pipeline_1_fu_76_gate_f_ce0;
wire    grp_infer_Pipeline_1_fu_76_gate_f_we0;
wire   [31:0] grp_infer_Pipeline_1_fu_76_gate_f_d0;
wire    grp_infer_Pipeline_2_fu_82_ap_start;
wire    grp_infer_Pipeline_2_fu_82_ap_done;
wire    grp_infer_Pipeline_2_fu_82_ap_idle;
wire    grp_infer_Pipeline_2_fu_82_ap_ready;
wire   [6:0] grp_infer_Pipeline_2_fu_82_gate_i_address0;
wire    grp_infer_Pipeline_2_fu_82_gate_i_ce0;
wire    grp_infer_Pipeline_2_fu_82_gate_i_we0;
wire   [31:0] grp_infer_Pipeline_2_fu_82_gate_i_d0;
wire    grp_infer_Pipeline_3_fu_88_ap_start;
wire    grp_infer_Pipeline_3_fu_88_ap_done;
wire    grp_infer_Pipeline_3_fu_88_ap_idle;
wire    grp_infer_Pipeline_3_fu_88_ap_ready;
wire   [6:0] grp_infer_Pipeline_3_fu_88_stat_C_address0;
wire    grp_infer_Pipeline_3_fu_88_stat_C_ce0;
wire    grp_infer_Pipeline_3_fu_88_stat_C_we0;
wire   [31:0] grp_infer_Pipeline_3_fu_88_stat_C_d0;
wire    grp_infer_Pipeline_4_fu_94_ap_start;
wire    grp_infer_Pipeline_4_fu_94_ap_done;
wire    grp_infer_Pipeline_4_fu_94_ap_idle;
wire    grp_infer_Pipeline_4_fu_94_ap_ready;
wire   [6:0] grp_infer_Pipeline_4_fu_94_C_t_address0;
wire    grp_infer_Pipeline_4_fu_94_C_t_ce0;
wire    grp_infer_Pipeline_4_fu_94_C_t_we0;
wire   [31:0] grp_infer_Pipeline_4_fu_94_C_t_d0;
wire    grp_infer_Pipeline_5_fu_100_ap_start;
wire    grp_infer_Pipeline_5_fu_100_ap_done;
wire    grp_infer_Pipeline_5_fu_100_ap_idle;
wire    grp_infer_Pipeline_5_fu_100_ap_ready;
wire   [6:0] grp_infer_Pipeline_5_fu_100_gate_o_address0;
wire    grp_infer_Pipeline_5_fu_100_gate_o_ce0;
wire    grp_infer_Pipeline_5_fu_100_gate_o_we0;
wire   [31:0] grp_infer_Pipeline_5_fu_100_gate_o_d0;
wire    grp_infer_Pipeline_6_fu_106_ap_start;
wire    grp_infer_Pipeline_6_fu_106_ap_done;
wire    grp_infer_Pipeline_6_fu_106_ap_idle;
wire    grp_infer_Pipeline_6_fu_106_ap_ready;
wire   [6:0] grp_infer_Pipeline_6_fu_106_h_t_address0;
wire    grp_infer_Pipeline_6_fu_106_h_t_ce0;
wire    grp_infer_Pipeline_6_fu_106_h_t_we0;
wire   [31:0] grp_infer_Pipeline_6_fu_106_h_t_d0;
wire    grp_infer_Pipeline_32_fu_112_ap_start;
wire    grp_infer_Pipeline_32_fu_112_ap_done;
wire    grp_infer_Pipeline_32_fu_112_ap_idle;
wire    grp_infer_Pipeline_32_fu_112_ap_ready;
wire   [3:0] grp_infer_Pipeline_32_fu_112_res_address0;
wire    grp_infer_Pipeline_32_fu_112_res_ce0;
wire    grp_infer_Pipeline_32_fu_112_res_we0;
wire   [31:0] grp_infer_Pipeline_32_fu_112_res_d0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_done;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_idle;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_ready;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_ce0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_we0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_d0;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_address1;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_ce1;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_ce0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_we0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_d0;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_ce0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_we0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_d0;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_address1;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_ce1;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_ce0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_we0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_d0;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_ce0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_we0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_d0;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_address1;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_ce1;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_ce0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_we0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_d0;
wire   [6:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_address1;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_ce1;
wire   [9:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_input_r_address0;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_input_r_ce0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_din0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_din1;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_ce;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_din0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_din1;
wire   [1:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_opcode;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_ce;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_din0;
wire   [31:0] grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_din1;
wire    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_ce;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_done;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_idle;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_ready;
wire   [6:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_h_t_address0;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_h_t_ce0;
wire   [3:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_address0;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_ce0;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_we0;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_d0;
wire   [3:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_address1;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_ce1;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_din0;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_din1;
wire   [1:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_opcode;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_ce;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_din0;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_din1;
wire    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_ce;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_done;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_idle;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_ready;
wire   [3:0] grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_address0;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_ce0;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_we0;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_d0;
wire   [3:0] grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_address1;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_ce1;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_din0;
wire   [31:0] grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_din1;
wire   [1:0] grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_opcode;
wire    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_ce;
reg    grp_infer_Pipeline_1_fu_76_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_infer_Pipeline_2_fu_82_ap_start_reg;
reg    grp_infer_Pipeline_3_fu_88_ap_start_reg;
reg    grp_infer_Pipeline_4_fu_94_ap_start_reg;
reg    grp_infer_Pipeline_5_fu_100_ap_start_reg;
reg    grp_infer_Pipeline_6_fu_106_ap_start_reg;
reg    grp_infer_Pipeline_32_fu_112_ap_start_reg;
reg    grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_fu_169_p2;
reg   [31:0] grp_fu_169_p0;
reg   [31:0] grp_fu_169_p1;
reg    grp_fu_169_ce;
wire   [31:0] grp_fu_173_p2;
reg   [31:0] grp_fu_173_p0;
reg   [31:0] grp_fu_173_p1;
reg    grp_fu_173_ce;
reg    grp_fu_177_ce;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_infer_Pipeline_1_fu_76_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_2_fu_82_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_3_fu_88_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_4_fu_94_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_5_fu_100_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_6_fu_106_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_32_fu_112_ap_start_reg = 1'b0;
#0 grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start_reg = 1'b0;
#0 grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start_reg = 1'b0;
end

LSTM_Top_infer_gate_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
gate_f_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gate_f_address0),
    .ce0(gate_f_ce0),
    .we0(gate_f_we0),
    .d0(gate_f_d0),
    .q0(gate_f_q0),
    .address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_address1),
    .ce1(gate_f_ce1),
    .q1(gate_f_q1)
);

LSTM_Top_infer_gate_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
gate_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gate_i_address0),
    .ce0(gate_i_ce0),
    .we0(gate_i_we0),
    .d0(gate_i_d0),
    .q0(gate_i_q0),
    .address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_address1),
    .ce1(gate_i_ce1),
    .q1(gate_i_q1)
);

LSTM_Top_infer_gate_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
stat_C_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(stat_C_address0),
    .ce0(stat_C_ce0),
    .we0(stat_C_we0),
    .d0(stat_C_d0),
    .q0(stat_C_q0),
    .address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_address1),
    .ce1(stat_C_ce1),
    .q1(stat_C_q1)
);

LSTM_Top_infer_C_t_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
C_t_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(C_t_address0),
    .ce0(C_t_ce0),
    .we0(C_t_we0),
    .d0(C_t_d0),
    .q0(C_t_q0)
);

LSTM_Top_infer_gate_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
gate_o_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gate_o_address0),
    .ce0(gate_o_ce0),
    .we0(gate_o_we0),
    .d0(gate_o_d0),
    .q0(gate_o_q0),
    .address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_address1),
    .ce1(gate_o_ce1),
    .q1(gate_o_q1)
);

LSTM_Top_infer_C_t_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
h_t_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(h_t_address0),
    .ce0(h_t_ce0),
    .we0(h_t_we0),
    .d0(h_t_d0),
    .q0(h_t_q0)
);

LSTM_Top_infer_Pipeline_1 grp_infer_Pipeline_1_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_1_fu_76_ap_start),
    .ap_done(grp_infer_Pipeline_1_fu_76_ap_done),
    .ap_idle(grp_infer_Pipeline_1_fu_76_ap_idle),
    .ap_ready(grp_infer_Pipeline_1_fu_76_ap_ready),
    .gate_f_address0(grp_infer_Pipeline_1_fu_76_gate_f_address0),
    .gate_f_ce0(grp_infer_Pipeline_1_fu_76_gate_f_ce0),
    .gate_f_we0(grp_infer_Pipeline_1_fu_76_gate_f_we0),
    .gate_f_d0(grp_infer_Pipeline_1_fu_76_gate_f_d0)
);

LSTM_Top_infer_Pipeline_2 grp_infer_Pipeline_2_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_2_fu_82_ap_start),
    .ap_done(grp_infer_Pipeline_2_fu_82_ap_done),
    .ap_idle(grp_infer_Pipeline_2_fu_82_ap_idle),
    .ap_ready(grp_infer_Pipeline_2_fu_82_ap_ready),
    .gate_i_address0(grp_infer_Pipeline_2_fu_82_gate_i_address0),
    .gate_i_ce0(grp_infer_Pipeline_2_fu_82_gate_i_ce0),
    .gate_i_we0(grp_infer_Pipeline_2_fu_82_gate_i_we0),
    .gate_i_d0(grp_infer_Pipeline_2_fu_82_gate_i_d0)
);

LSTM_Top_infer_Pipeline_3 grp_infer_Pipeline_3_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_3_fu_88_ap_start),
    .ap_done(grp_infer_Pipeline_3_fu_88_ap_done),
    .ap_idle(grp_infer_Pipeline_3_fu_88_ap_idle),
    .ap_ready(grp_infer_Pipeline_3_fu_88_ap_ready),
    .stat_C_address0(grp_infer_Pipeline_3_fu_88_stat_C_address0),
    .stat_C_ce0(grp_infer_Pipeline_3_fu_88_stat_C_ce0),
    .stat_C_we0(grp_infer_Pipeline_3_fu_88_stat_C_we0),
    .stat_C_d0(grp_infer_Pipeline_3_fu_88_stat_C_d0)
);

LSTM_Top_infer_Pipeline_4 grp_infer_Pipeline_4_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_4_fu_94_ap_start),
    .ap_done(grp_infer_Pipeline_4_fu_94_ap_done),
    .ap_idle(grp_infer_Pipeline_4_fu_94_ap_idle),
    .ap_ready(grp_infer_Pipeline_4_fu_94_ap_ready),
    .C_t_address0(grp_infer_Pipeline_4_fu_94_C_t_address0),
    .C_t_ce0(grp_infer_Pipeline_4_fu_94_C_t_ce0),
    .C_t_we0(grp_infer_Pipeline_4_fu_94_C_t_we0),
    .C_t_d0(grp_infer_Pipeline_4_fu_94_C_t_d0)
);

LSTM_Top_infer_Pipeline_5 grp_infer_Pipeline_5_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_5_fu_100_ap_start),
    .ap_done(grp_infer_Pipeline_5_fu_100_ap_done),
    .ap_idle(grp_infer_Pipeline_5_fu_100_ap_idle),
    .ap_ready(grp_infer_Pipeline_5_fu_100_ap_ready),
    .gate_o_address0(grp_infer_Pipeline_5_fu_100_gate_o_address0),
    .gate_o_ce0(grp_infer_Pipeline_5_fu_100_gate_o_ce0),
    .gate_o_we0(grp_infer_Pipeline_5_fu_100_gate_o_we0),
    .gate_o_d0(grp_infer_Pipeline_5_fu_100_gate_o_d0)
);

LSTM_Top_infer_Pipeline_6 grp_infer_Pipeline_6_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_6_fu_106_ap_start),
    .ap_done(grp_infer_Pipeline_6_fu_106_ap_done),
    .ap_idle(grp_infer_Pipeline_6_fu_106_ap_idle),
    .ap_ready(grp_infer_Pipeline_6_fu_106_ap_ready),
    .h_t_address0(grp_infer_Pipeline_6_fu_106_h_t_address0),
    .h_t_ce0(grp_infer_Pipeline_6_fu_106_h_t_ce0),
    .h_t_we0(grp_infer_Pipeline_6_fu_106_h_t_we0),
    .h_t_d0(grp_infer_Pipeline_6_fu_106_h_t_d0)
);

LSTM_Top_infer_Pipeline_32 grp_infer_Pipeline_32_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_32_fu_112_ap_start),
    .ap_done(grp_infer_Pipeline_32_fu_112_ap_done),
    .ap_idle(grp_infer_Pipeline_32_fu_112_ap_idle),
    .ap_ready(grp_infer_Pipeline_32_fu_112_ap_ready),
    .res_address0(grp_infer_Pipeline_32_fu_112_res_address0),
    .res_ce0(grp_infer_Pipeline_32_fu_112_res_ce0),
    .res_we0(grp_infer_Pipeline_32_fu_112_res_we0),
    .res_d0(grp_infer_Pipeline_32_fu_112_res_d0)
);

LSTM_Top_infer_Outline_VITIS_LOOP_63_1 grp_infer_Outline_VITIS_LOOP_63_1_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start),
    .ap_done(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_done),
    .ap_idle(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_idle),
    .ap_ready(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_ready),
    .gate_o_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_address0),
    .gate_o_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_ce0),
    .gate_o_we0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_we0),
    .gate_o_d0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_d0),
    .gate_o_q0(gate_o_q0),
    .gate_o_address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_address1),
    .gate_o_ce1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_ce1),
    .gate_o_q1(gate_o_q1),
    .h_t_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_address0),
    .h_t_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_ce0),
    .h_t_we0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_we0),
    .h_t_d0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_d0),
    .h_t_q0(h_t_q0),
    .stat_C_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_address0),
    .stat_C_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_ce0),
    .stat_C_we0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_we0),
    .stat_C_d0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_d0),
    .stat_C_q0(stat_C_q0),
    .stat_C_address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_address1),
    .stat_C_ce1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_ce1),
    .stat_C_q1(stat_C_q1),
    .C_t_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_address0),
    .C_t_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_ce0),
    .C_t_we0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_we0),
    .C_t_d0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_d0),
    .C_t_q0(C_t_q0),
    .gate_i_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_address0),
    .gate_i_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_ce0),
    .gate_i_we0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_we0),
    .gate_i_d0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_d0),
    .gate_i_q0(gate_i_q0),
    .gate_i_address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_address1),
    .gate_i_ce1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_ce1),
    .gate_i_q1(gate_i_q1),
    .gate_f_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_address0),
    .gate_f_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_ce0),
    .gate_f_we0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_we0),
    .gate_f_d0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_d0),
    .gate_f_q0(gate_f_q0),
    .gate_f_address1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_address1),
    .gate_f_ce1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_ce1),
    .gate_f_q1(gate_f_q1),
    .input_r_address0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_input_r_address0),
    .input_r_ce0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_input_r_ce0),
    .input_r_q0(input_r_q0),
    .grp_fu_169_p_din0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_din1),
    .grp_fu_169_p_dout0(grp_fu_169_p2),
    .grp_fu_169_p_ce(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_ce),
    .grp_fu_173_p_din0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_din1),
    .grp_fu_173_p_opcode(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_opcode),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_ce),
    .grp_fu_177_p_din0(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_din0),
    .grp_fu_177_p_din1(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_din1),
    .grp_fu_177_p_dout0(grp_fu_114_p_dout0),
    .grp_fu_177_p_ce(grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_ce)
);

LSTM_Top_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13 grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start),
    .ap_done(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_done),
    .ap_idle(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_idle),
    .ap_ready(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_ready),
    .h_t_address0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_h_t_address0),
    .h_t_ce0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_h_t_ce0),
    .h_t_q0(h_t_q0),
    .res_address0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_address0),
    .res_ce0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_ce0),
    .res_we0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_we0),
    .res_d0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_d0),
    .res_address1(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_address1),
    .res_ce1(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_ce1),
    .res_q1(res_q1),
    .grp_fu_173_p_din0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_din1),
    .grp_fu_173_p_opcode(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_opcode),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_ce),
    .grp_fu_169_p_din0(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_din1),
    .grp_fu_169_p_dout0(grp_fu_169_p2),
    .grp_fu_169_p_ce(grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_ce)
);

LSTM_Top_infer_Pipeline_VITIS_LOOP_34_110 grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start),
    .ap_done(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_done),
    .ap_idle(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_idle),
    .ap_ready(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_ready),
    .res_address0(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_address0),
    .res_ce0(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_ce0),
    .res_we0(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_we0),
    .res_d0(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_d0),
    .res_address1(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_address1),
    .res_ce1(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_ce1),
    .res_q1(res_q1),
    .grp_fu_173_p_din0(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_din1),
    .grp_fu_173_p_opcode(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_opcode),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_ce)
);

LSTM_Top_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U146(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_169_p0),
    .din1(grp_fu_169_p1),
    .ce(grp_fu_169_ce),
    .dout(grp_fu_169_p2)
);

LSTM_Top_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U147(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_173_p0),
    .din1(grp_fu_173_p1),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_ready == 1'b1)) begin
            grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_1_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_1_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_1_fu_76_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_1_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_2_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_2_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_2_fu_82_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_2_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_32_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_32_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_32_fu_112_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_32_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_3_fu_88_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_3_fu_88_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_3_fu_88_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_3_fu_88_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_4_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_4_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_4_fu_94_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_4_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_5_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_5_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_5_fu_100_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_5_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_6_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_infer_Pipeline_6_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_6_fu_106_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_6_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_ready == 1'b1)) begin
            grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_t_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_t_address0 = grp_infer_Pipeline_4_fu_94_C_t_address0;
    end else begin
        C_t_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_t_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_t_ce0 = grp_infer_Pipeline_4_fu_94_C_t_ce0;
    end else begin
        C_t_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_t_d0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_t_d0 = grp_infer_Pipeline_4_fu_94_C_t_d0;
    end else begin
        C_t_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        C_t_we0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_C_t_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_t_we0 = grp_infer_Pipeline_4_fu_94_C_t_we0;
    end else begin
        C_t_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_f_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_f_address0 = grp_infer_Pipeline_1_fu_76_gate_f_address0;
    end else begin
        gate_f_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_f_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_f_ce0 = grp_infer_Pipeline_1_fu_76_gate_f_ce0;
    end else begin
        gate_f_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_f_ce1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_ce1;
    end else begin
        gate_f_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_f_d0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_f_d0 = grp_infer_Pipeline_1_fu_76_gate_f_d0;
    end else begin
        gate_f_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_f_we0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_f_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_f_we0 = grp_infer_Pipeline_1_fu_76_gate_f_we0;
    end else begin
        gate_f_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_i_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_i_address0 = grp_infer_Pipeline_2_fu_82_gate_i_address0;
    end else begin
        gate_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_i_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_i_ce0 = grp_infer_Pipeline_2_fu_82_gate_i_ce0;
    end else begin
        gate_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_i_ce1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_ce1;
    end else begin
        gate_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_i_d0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_i_d0 = grp_infer_Pipeline_2_fu_82_gate_i_d0;
    end else begin
        gate_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_i_we0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_i_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_i_we0 = grp_infer_Pipeline_2_fu_82_gate_i_we0;
    end else begin
        gate_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_o_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_o_address0 = grp_infer_Pipeline_5_fu_100_gate_o_address0;
    end else begin
        gate_o_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_o_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_o_ce0 = grp_infer_Pipeline_5_fu_100_gate_o_ce0;
    end else begin
        gate_o_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_o_ce1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_ce1;
    end else begin
        gate_o_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_o_d0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_o_d0 = grp_infer_Pipeline_5_fu_100_gate_o_d0;
    end else begin
        gate_o_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gate_o_we0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_gate_o_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        gate_o_we0 = grp_infer_Pipeline_5_fu_100_gate_o_we0;
    end else begin
        gate_o_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_169_ce = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_ce = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_ce;
    end else begin
        grp_fu_169_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_169_p0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_p0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_din0;
    end else begin
        grp_fu_169_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_169_p1 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_169_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_p1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_169_p_din1;
    end else begin
        grp_fu_169_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_173_ce = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_173_ce = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_ce = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_ce;
    end else begin
        grp_fu_173_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_173_p0 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_173_p0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_p0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_din0;
    end else begin
        grp_fu_173_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_173_p1 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_grp_fu_173_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_173_p1 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_grp_fu_173_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_p1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_173_p_din1;
    end else begin
        grp_fu_173_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_177_ce = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_ce;
    end else begin
        grp_fu_177_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        h_t_address0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_h_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        h_t_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_t_address0 = grp_infer_Pipeline_6_fu_106_h_t_address0;
    end else begin
        h_t_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        h_t_ce0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_h_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        h_t_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_t_ce0 = grp_infer_Pipeline_6_fu_106_h_t_ce0;
    end else begin
        h_t_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_t_d0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_t_d0 = grp_infer_Pipeline_6_fu_106_h_t_d0;
    end else begin
        h_t_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_t_we0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_h_t_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_t_we0 = grp_infer_Pipeline_6_fu_106_h_t_we0;
    end else begin
        h_t_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        res_address0 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        res_address0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        res_address0 = grp_infer_Pipeline_32_fu_112_res_address0;
    end else begin
        res_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        res_address1 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        res_address1 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_address1;
    end else begin
        res_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        res_ce0 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        res_ce0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        res_ce0 = grp_infer_Pipeline_32_fu_112_res_ce0;
    end else begin
        res_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        res_ce1 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        res_ce1 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_ce1;
    end else begin
        res_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        res_d0 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        res_d0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        res_d0 = grp_infer_Pipeline_32_fu_112_res_d0;
    end else begin
        res_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        res_we0 = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_res_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        res_we0 = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_res_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        res_we0 = grp_infer_Pipeline_32_fu_112_res_we0;
    end else begin
        res_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stat_C_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        stat_C_address0 = grp_infer_Pipeline_3_fu_88_stat_C_address0;
    end else begin
        stat_C_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stat_C_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        stat_C_ce0 = grp_infer_Pipeline_3_fu_88_stat_C_ce0;
    end else begin
        stat_C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stat_C_ce1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_ce1;
    end else begin
        stat_C_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stat_C_d0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        stat_C_d0 = grp_infer_Pipeline_3_fu_88_stat_C_d0;
    end else begin
        stat_C_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stat_C_we0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_stat_C_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        stat_C_we0 = grp_infer_Pipeline_3_fu_88_stat_C_we0;
    end else begin
        stat_C_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_infer_Pipeline_32_fu_112_ap_done == 1'b0) | (grp_infer_Pipeline_6_fu_106_ap_done == 1'b0) | (grp_infer_Pipeline_5_fu_100_ap_done == 1'b0) | (grp_infer_Pipeline_4_fu_94_ap_done == 1'b0) | (grp_infer_Pipeline_3_fu_88_ap_done == 1'b0) | (grp_infer_Pipeline_2_fu_82_ap_done == 1'b0) | (grp_infer_Pipeline_1_fu_76_ap_done == 1'b0));
end

assign grp_fu_114_p_ce = grp_fu_177_ce;

assign grp_fu_114_p_din0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_din0;

assign grp_fu_114_p_din1 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_grp_fu_177_p_din1;

assign grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_ap_start_reg;

assign grp_infer_Pipeline_1_fu_76_ap_start = grp_infer_Pipeline_1_fu_76_ap_start_reg;

assign grp_infer_Pipeline_2_fu_82_ap_start = grp_infer_Pipeline_2_fu_82_ap_start_reg;

assign grp_infer_Pipeline_32_fu_112_ap_start = grp_infer_Pipeline_32_fu_112_ap_start_reg;

assign grp_infer_Pipeline_3_fu_88_ap_start = grp_infer_Pipeline_3_fu_88_ap_start_reg;

assign grp_infer_Pipeline_4_fu_94_ap_start = grp_infer_Pipeline_4_fu_94_ap_start_reg;

assign grp_infer_Pipeline_5_fu_100_ap_start = grp_infer_Pipeline_5_fu_100_ap_start_reg;

assign grp_infer_Pipeline_6_fu_106_ap_start = grp_infer_Pipeline_6_fu_106_ap_start_reg;

assign grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start = grp_infer_Pipeline_VITIS_LOOP_141_12_VITIS_LOOP_141_13_fu_152_ap_start_reg;

assign grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start = grp_infer_Pipeline_VITIS_LOOP_34_110_fu_161_ap_start_reg;

assign input_r_address0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_input_r_address0;

assign input_r_ce0 = grp_infer_Outline_VITIS_LOOP_63_1_fu_118_input_r_ce0;

endmodule //LSTM_Top_infer
