// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fill_n.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fill_n::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fill_n::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> fill_n::ap_ST_fsm_state1 = "1";
const sc_lv<2> fill_n::ap_ST_fsm_state2 = "10";
const sc_lv<32> fill_n::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fill_n::ap_const_lv32_1 = "1";
const sc_lv<8> fill_n::ap_const_lv8_0 = "00000000";
const sc_lv<1> fill_n::ap_const_lv1_0 = "0";
const sc_lv<8> fill_n::ap_const_lv8_80 = "10000000";
const sc_lv<8> fill_n::ap_const_lv8_1 = "1";
const sc_lv<1> fill_n::ap_const_lv1_1 = "1";
const bool fill_n::ap_const_boolean_1 = true;

fill_n::fill_n(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln762_fu_52_p2);
    sensitive << ( p_0_rec_i_reg_30 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln762_fu_46_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln762_fu_46_p2 );

    SC_METHOD(thread_icmp_ln762_fu_46_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_0_rec_i_reg_30 );

    SC_METHOD(thread_p_0_rec_i_cast_fu_41_p1);
    sensitive << ( p_0_rec_i_reg_30 );

    SC_METHOD(thread_p_first_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_0_rec_i_cast_fu_41_p1 );

    SC_METHOD(thread_p_first_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_p_first_d0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_p_first_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln762_fu_46_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln762_fu_46_p2 );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fill_n_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_first_address0, "(port)p_first_address0");
    sc_trace(mVcdFile, p_first_ce0, "(port)p_first_ce0");
    sc_trace(mVcdFile, p_first_we0, "(port)p_first_we0");
    sc_trace(mVcdFile, p_first_d0, "(port)p_first_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, add_ln762_fu_52_p2, "add_ln762_fu_52_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, p_0_rec_i_reg_30, "p_0_rec_i_reg_30");
    sc_trace(mVcdFile, icmp_ln762_fu_46_p2, "icmp_ln762_fu_46_p2");
    sc_trace(mVcdFile, p_0_rec_i_cast_fu_41_p1, "p_0_rec_i_cast_fu_41_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fill_n::~fill_n() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void fill_n::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln762_fu_46_p2.read(), ap_const_lv1_0))) {
        p_0_rec_i_reg_30 = add_ln762_fu_52_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_0_rec_i_reg_30 = ap_const_lv8_0;
    }
}

void fill_n::thread_add_ln762_fu_52_p2() {
    add_ln762_fu_52_p2 = (!p_0_rec_i_reg_30.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_0_rec_i_reg_30.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fill_n::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fill_n::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fill_n::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln762_fu_46_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fill_n::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fill_n::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln762_fu_46_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fill_n::thread_icmp_ln762_fu_46_p2() {
    icmp_ln762_fu_46_p2 = (!p_0_rec_i_reg_30.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(p_0_rec_i_reg_30.read() == ap_const_lv8_80);
}

void fill_n::thread_p_0_rec_i_cast_fu_41_p1() {
    p_0_rec_i_cast_fu_41_p1 = esl_zext<64,8>(p_0_rec_i_reg_30.read());
}

void fill_n::thread_p_first_address0() {
    p_first_address0 =  (sc_lv<7>) (p_0_rec_i_cast_fu_41_p1.read());
}

void fill_n::thread_p_first_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_first_ce0 = ap_const_logic_1;
    } else {
        p_first_ce0 = ap_const_logic_0;
    }
}

void fill_n::thread_p_first_d0() {
    p_first_d0 = ap_const_lv32_0;
}

void fill_n::thread_p_first_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln762_fu_46_p2.read(), ap_const_lv1_0))) {
        p_first_we0 = ap_const_logic_1;
    } else {
        p_first_we0 = ap_const_logic_0;
    }
}

void fill_n::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln762_fu_46_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

